# Generated by Django 5.1.5 on 2025-01-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('IP', models.GenericIPAddressField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
