# Generated by Django 5.1.5 on 2025-01-15 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_instafunctype_instahistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='instahistory',
            name='insta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='insta.insta'),
            preserve_default=False,
        ),
    ]
